micronutrients = {
    "energy": "Energy (kcal)",
    "calories": "Energy (kcal)", 
    "water": "Water (g)", 
    "b1 (thiamine)": "B1 (Thiamine) (mg)",
    "b1": "B1 (Thiamine) (mg)", 
    "thiamine": "B1 (Thiamine) (mg)",
    "b2 (riboflavin)": "B2 (Riboflavin) (mg)",
    "b2": "B2 (Riboflavin) (mg)", 
    "riboflavin": "B2 (Riboflavin) (mg)",
    "b3 (niacin)": "B3 (Niacin) (mg)",
    "b3": "B3 (Niacin) (mg)", 
    "niacin": "B3 (Niacin) (mg)",
    "b5 (pantothenic acid)": "B5 (Pantothenic Acid) (mg)",
    "b5": "B5 (Pantothenic Acid) (mg)", 
    "pantothenic acid": "B5 (Pantothenic Acid) (mg)",
    "b6 (pyridoxine)": "B6 (Pyridoxine) (mg)",
    "b6": "B6 (Pyridoxine) (mg)", 
    "pyridoxine": "B6 (Pyridoxine) (mg)",
    "b12 (cobalamin)": "B12 (Cobalamin) (µg)", 
    "b12": "B12 (Cobalamin) (µg)", 
    "cobalamin": "B12 (Cobalamin) (µg)", 
    "alpha-carotene": "Alpha-carotene (µg)", 
    "beta tocopherol": "Beta Tocopherol (mg)", 
    "beta-carotene": "Beta-carotene (µg)", 
    "beta-cryptoxanthin": "Beta-cryptoxanthin (µg)", 
    "biotin": "Biotin (µg)", 
    "choline": "Choline (mg)", 
    "delta tocopherol": "Delta Tocopherol (mg)", 
    "folate": "Folate (µg)", 
    "gamma tocopherol": 
    "Gamma Tocopherol (mg)", 
    "lutein+zeaxanthin": "Lutein+Zeaxanthin (µg)", 
    "lycopene": "Lycopene (µg)", 
    "retinol": "Retinol (µg)", 
    "vitamin a": "Vitamin A (µg)", 
    "vitamin c": "Vitamin C (mg)", 
    "vitamin d": "Vitamin D (IU)", 
    "vitamin e": "Vitamin E (mg)", 
    "vitamin k": "Vitamin K (µg)", 
    "calcium": "Calcium (mg)", 
    "chromium": "Chromium (µg)", 
    "copper": "Copper (mg)", 
    "iodine": "Iodine (µg)", 
    "iron": "Iron (mg)", 
    "magnesium": "Magnesium (mg)", 
    "manganese": "Manganese (mg)", 
    "molybdenum": "Molybdenum (µg)", 
    "phosphorus": "Phosphorus (mg)", 
    "potassium": "Potassium (mg)", 
    "selenium": "Selenium (µg)", 
    "sodium": "Sodium (mg)", 
    "zinc": "Zinc (mg)", 
    "carbs": "Carbs (g)", 
    "fiber": "Fiber (g)", 
    "sugars": "Sugars (g)", 
    "added sugars": "Added Sugars (g)", 
    "net carbs": "Net Carbs (g)", 
    "fat": "Fat (g)", 
    "cholesterol": "Cholesterol (mg)", 
    "monounsaturated": "Monounsaturated (g)", 
    "polyunsaturated": "Polyunsaturated (g)", 
    "saturated": "Saturated (g)", 
    "trans-fats": "Trans-Fats (g)", 
    "trans-fat": "Trans-Fats (g)", 
    "trans fats": "Trans-Fats (g)", 
    "trans-fat": "Trans-Fats (g)", 
    "omega-3": "Omega-3 (g)", 
    "omega-6": "Omega-6 (g)", 
    "cystine": "Cystine (g)", 
    "histidine": "Histidine (g)", 
    "isoleucine": "Isoleucine (g)", 
    "leucine": "Leucine (g)", 
    "lysine": "Lysine (g)", 
    "methionine": "Methionine (g)", 
    "phenylalanine": "Phenylalanine (g)", 
    "protein": "Protein (g)", 
    "threonine": "Threonine (g)", 
    "tryptophan": "Tryptophan (g)", 
    "tyrosine": "Tyrosine (g)", 
    "valine": "Valine (g)"
}